trigger:
  batch: true
  branches:
    include:
    - master
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/

parameters:
- name: includeMacOS
  displayName: Build on macOS
  type: boolean
  default: true # macOS is often bogged down in Azure Pipelines

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  codecov_token: # Get a new one from https://codecov.io/
  ci_feed: CI # Azure Artifacts feed name
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- template: azure-pipelines/build.yml
  parameters:
    includeMacOS: ${{ parameters.includeMacOS }}
